---
# tasks file for genlinux

  - name: set grub config
    command: grubby --update-kernel=ALL --args='console=ttyS0 earlyprintk=ttyS0 rootdelay=300 numa=off'

  - name: remove udev net rules
    file:  path=/etc/udev/rules.d/70-persistent-net.rules state=absent

  - name: remove udev generator rules
    file:  path=/etc/udev/rules.d/75-persistent-net-generator.rules state=absent

